### ISSUE TITLE
[Pymode]: error: invalid load key, 'A'.

### ISSUE THREAD

**Issue by wangshunping** [liangxianzhe/oh-my-vim#10]
[Pymode] Regenerate Rope cache ...  
[Pymode]: error: invalid load key, 'A'.
Press ENTER or type command to continue

Hi ,Thanks for your oh-my-vim, I like it although i don't know it 100percent.
But now when i :w every time, there is an error, it is annoying....

Can you teach me how to fix it ~
Thanks a million

if you are a Chinese , you can teach me in Chinese 
Thanks a million~

**Comment by liangxianzhe** [comment]
Sorry. This project is not longer maintained. See Readme for deprecation notice.
