### ISSUE TITLE
Override Default Line Numbering

### ISSUE THREAD

**Issue by wazery** [liangxianzhe/oh-my-vim#11]
I want to change the default line numbering mode to absolute, how to add that to my config?

Also how to remove the `none` mode from being switched to using the `Leader key + l`?

**Comment by wazery** [comment]
I figured out the answer for the first question, here is what I used `norelativenumber`.

I hope someone point me a way for the second question.

**Comment by sindhus** [comment]
@wazery do i put in `set norelativenumber` every time i start vim in Command mode? or do I have to put in some file? Thanks!

**Comment by liangxianzhe** [comment]
@wazery You can put `set norelativenumber` in ~/.after.vimrc
As for removing remove the none mode, you can fork and change this function https://github.com/liangxianzhe/oh-my-vim/blob/master/packages/text.vimrc#L36

**Comment by simonkeng** [comment]
Thank you @liangxianzhe, this is very helpful.
