### ISSUE TITLE
Errors from neobundle at launch

### ISSUE THREAD

**Issue by etiennebatise** [liangxianzhe/oh-my-vim#15]
Few days ago, I had the same problem as #13 . After a new update the errors were different.

```
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.
```

I'm not familiar with vim plugins and I can't locate the problem.

**Comment by cksun** [comment]
In vimrc file, you can move "call neobundle#end()" after the line "END IMPORT PACKAGES }}}" to get rid of this error.

**Comment by etiennebatise** [comment]
Perfect, thanks !

**Comment by hamoid** [comment]
I'm having the same issue, and there's no "END IMPORT PACKAGES" in my .vimrc. How can I fix it?

This is the beginning of my .vimrc file:

```
" vim: set fdm=marker :

" #Bundles {{{
" Bundler that knows how to 'make' "{{{
if has('vim_starting')
  set nocompatible               " Be iMproved
  set runtimepath+=~/.vim/bundle/neobundle.vim/
  set timeoutlen=1000 ttimeoutlen=10
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

call neobundle#end()
"}}}
```

**Comment by etiennebatise** [comment]
My problem was that this line : 
*  https://github.com/liangxianzhe/oh-my-vim/blob/master/vimrc#L147

Has to be here : 
* https://github.com/liangxianzhe/oh-my-vim/blob/master/vimrc#L164

**Comment by hamoid** [comment]
Thanks. I rearranged the whole file and now it works. I had each Bundle loading together with the config settings related to that bundle. Now I have all the loading at the top, and the config below. More confusing but it works.

**Comment by etiennebatise** [comment]
I can't find the link for the moment but I think it is possible to use a sort of `neobundle append` function to have several blocks of Neobundle configuration in multiple locations. 

I'm glad you've solved your problem. :+1:

**Comment by royss7** [comment]
I faced with the same problem as yours, and when I just moved "call neobundle#end()" to line 164, a new problem would arise :
![2015-06-12 16 32 03](https://cloud.githubusercontent.com/assets/3397707/8126392/afffd4d6-1120-11e5-8bb1-99a86c5e398f.png)
and the color scheme can not work, the vim just like : 
![2015-06-12 16 34 26](https://cloud.githubusercontent.com/assets/3397707/8126418/eda8a326-1120-11e5-8e7d-9585d006121d.png)
so I thought maybe 'basic' is not depended on 'neobundle' and modified the vimdc as : 
![2015-06-12 16 38 57](https://cloud.githubusercontent.com/assets/3397707/8126496/8fcbab3a-1121-11e5-87ed-7dbf0281a556.png)

and now it works.
