### ISSUE TITLE
How to fold javascript functions?

### ISSUE THREAD

**Issue by sindhus** [liangxianzhe/oh-my-vim#16]
How do I fold functions (I am looking at a javascript file)?
space+e command has "toggle fold" but when I execute it, I get

```
/private/var/folders/zt/fghg3whn1px0_ndpww30wtsw0000gn/T/vW4uVzQ/126, line 1                                         
Vim(normal):E490: No fold found                                                                                      
Error occurred while executing "execute" action!                                                                     
Press ENTER or type command to continue
```

Am new to vim! but love that I am able to learn vim faster with your plugin setup. Thank you for writing this! Your docs are awesome.

**Comment by liangxianzhe** [comment]
I didn't include any plugin for javascript, you can try https://github.com/pangloss/vim-javascript maybe.
