### ISSUE TITLE
How to draw spaces with • symbol in grey?

### ISSUE THREAD

**Issue by sindhus** [liangxianzhe/oh-my-vim#17]
hi! thanks for writing this, this made me finally switch to vim after so many tries and it has most features I use in Sublime Text editor by default. I am unable to see whitespaces that may have creeped up while I write code. How do I draw spaces in all files with • except in grey? (just like Sublime Text) 

Is this possible?
Thanks.

**Comment by liangxianzhe** [comment]
See show hidden chars in https://github.com/liangxianzhe/oh-my-vim#text
