### ISSUE TITLE
turn off auto word suggestion?

### ISSUE THREAD

**Issue by sindhus** [liangxianzhe/oh-my-vim#19]
how do I turn off the auto work completion/ suggester thing? thanks!

**Comment by sindhus** [comment]
anyone?

**Comment by liangxianzhe** [comment]
,ea
https://github.com/liangxianzhe/oh-my-vim/blob/master/packages/code.vimrc#L136

**Comment by sindhus** [comment]
I turned it off by deleting neoautocomplete directory in `.oh-my-vim/bundle`
