### ISSUE TITLE
.oh-my-vim/tools/check_for_upgrade.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by sophatvathana** [liangxianzhe/oh-my-vim#20]
Hello, 
    After i have completed to install oh-my-vim i got .oh-my-vim/tools/check_for_upgrade.sh: Syntax error: "(" unexpected when i use vim command . I try to change #!/bin/sh to #!/bin/bash or #!/usr/bin/zsh
still not work .. Please help !! Thank for advanced.. :)

**Comment by wulongtaxue** [comment]
@sophatvathana 
As for me, I just change "silent !**sh** $OH_MY_VIM/tools/check_for_upgrade.sh" in **~/.oh-my-vim/vimrc** to "silent !**bash** $OH_MY_VIM/tools/check_for_upgrade.sh".

**Comment by liangxianzhe** [comment]
What shell do you use?

**Comment by sophatvathana** [comment]
@wulongtaxue 
Yes it's work now thank you so much .. :laughing:
