### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by philcryer** [liangxianzhe/oh-my-vim#21]
From the readme:

> For Linux, you will need to figure out what the above script does, and install them according (apt-get etc). Please note a vim with lua support is needed. 

to satisfy the requirements, in Debian, I've gotten these to match up:

```
apt-get install ctags tig ranger lua5.2 luajit python-pip vim vim-nox
pip install pylint virtualenvwrapper coverage
```
But cannot find any packages that provide `ag` and `ack` - any clues to these? Has anyone else gotten this installed/running in Debian or Ubuntu? Thanks

**Comment by liangxianzhe** [comment]
Ag: https://github.com/ggreer/the_silver_searcher
Ack: http://beyondgrep.com/install/
