### ISSUE TITLE
Wiki missing

### ISSUE THREAD

**Issue by ghost** [liangxianzhe/oh-my-vim#22]
Hi,

I love what you have done with the whole configuration and I'm big fan of it. Please could you write detailed instruction how to add new plugins using neobundle and your configuration. I have marked that as an issue because there are a lot packages that could be installed and the whole process is complicated. I think I will drop using it if that part won't be covered.

Krystian

**Comment by Pk13055** [comment]
Also, in the meantime, would it be possible to add a list of all the visual (non-functional) plugins that have been used?

**Comment by liangxianzhe** [comment]
Sorry. This project is not longer maintained. See Readme for deprecation notice.
