### ISSUE TITLE
default curser move in insert-mode is weird

### ISSUE THREAD

**Issue by barontxu** [liangxianzhe/oh-my-vim#25]
default curser move in insert-mode is weird, how can I change it to origin version?

**Comment by do0g** [comment]
Comment https://github.com/liangxianzhe/oh-my-vim/blob/master/packages/basic.vimrc#L26
or create/edit .after.vimrc and add the line `set virtualedit=""`

For the record, however, I agree - I think this is an unusual, uncommon default.

**Comment by liangxianzhe** [comment]
Sorry. This project is not longer maintained. See Readme for deprecation notice.
