### ISSUE TITLE
How to disable strange navigation?

### ISSUE THREAD

**Issue by acesarski** [liangxianzhe/oh-my-vim#28]
Hey, how to disable this: 
![peek 2017-04-23 12-41](https://cloud.githubusercontent.com/assets/15309141/25312815/94bb44ba-2822-11e7-9d30-e81d6b56633c.gif)
I want default navigation without this endless row.

**Comment by do0g** [comment]
This is a dup of #25 

I've provided a workaround as a comment in that issue, but to reiterate I agree that this is an unusual default.

**Comment by liangxianzhe** [comment]
Sorry. This project is not longer maintained. See Readme for deprecation notice.
