### ISSUE TITLE
nerdtree

### ISSUE THREAD

**Issue by jayunit100** [liangxianzhe/oh-my-vim#35]
Hi ! whats the simplest way to get nerdtree into this great config?

**Comment by speedhog** [comment]
Hello Jay, you can install it by putting this on your .vimrc
   ` if has('vim_starting')`
`     set runtimepath+=~/.vim/bundle/neobundle.vim`
`    call neobundle#begin(expand('~/.vim/bundle/'))`
`    NeoBundle 'scrooloose/nerdtree'`
`call neobundle#end()`
`    endif`

Then you can simply run NeoBundle to install the plugin with this command on vim:
`:NeoBundleInstall`

Happy editing!

**Comment by jayunit100** [comment]
thanks :)

**Comment by jayunit100** [comment]
note this has to go on the END of the file :)
