### ISSUE TITLE
Suggestion of  mappings?

### ISSUE THREAD

**Issue by gu-fan** [liangxianzhe/oh-my-vim#4]
Thanks for your plugin and works.

I've had a try and think It have big potential~~(but still lots work to do~~)

I  think there should be a better way of modifing the mappings, like put them in a single file? (Also UI:font,theme,etc.)

Course I have lots of mappings defined in my vimrc, But I don't know whether they are conflict or what they are.

**Comment by liangxianzhe** [comment]
You can get a list of mappings using `:Unite mapping`, but it doesn't show conflicts.

However how to avoid conflict is truly a good question. I don't have a good answer yet.
