### ISSUE TITLE
the unite menu not working

### ISSUE THREAD

**Issue by eggcaker** [liangxianzhe/oh-my-vim#5]
after pressed `<LocalLeader>g`, the menu only show one item : 
![screen shot 2014-08-17 at 8 11 07 pm](https://cloud.githubusercontent.com/assets/21374/3944509/caabf14c-2608-11e4-97f8-c01f60c1e3c7.png)

iTerm2 
vim 7.4

**Comment by liangxianzhe** [comment]
Sorry for the late response. Could you try the latest version with a `:NeoBundleUpdate`?

Let me know if you still see the issue.
