### ISSUE TITLE
UltiSnips only works via `:set ft=python` and then `:set ft=<original filetype>`

### ISSUE THREAD

**Issue by nacnudus** [liangxianzhe/oh-my-vim#9]
If I do `vim temp.r` then `:set ft` says the filetype is "r", but r snippets don't work.  However, if I do `vim temp.r` then `:set ft=python`, then `:set ft=r`, then r snippets do work.

C files are the same -- I have to go via `:set ft=python` `:set ft=c`.

I have a clean install of oh-my-vim.

**Comment by liangxianzhe** [comment]
I think 051757d also fixes this issue. Could you have a try with latest version?
